### PR TITLE
changed bp-navbar to show bp-overflow only when there are more than 3 bp...

### PR DESCRIPTION
**Pull request by Goltergaul**
...-actions

I'm not sure if i fixed the tests correcty. can you check that for me please?

### CODE REVIEW

**Comment by Goltergaul** [comment]
#103

**Comment by Goltergaul** [comment]
[clabot:check]

**Comment by boennemann** [comment]
Hey @Goltergaul,

thanks for your patience here. I was playing with this and there seems to be one failing tests now: https://travis-ci.org/excellenteasy/bradypodion/builds/33779359

I'll look into this today, so we can get this released asap.

Stephan

**Comment by boennemann** [comment]
Thanks @Goltergaul,

this landed in 4ca242563c627119d6ed83cf49d115670a10adde and is available as 0.5.4 :+1:

**Comment by Goltergaul** [comment]
cool! :)

**Pull request closed without merging**
