### PR TITLE
Read up state from URL

### PR DESCRIPTION
**Pull request by boennemann**
@davidpfahler What do you think about reading `state.data.up` right from the url?
When a state has more than 1 URL segment we could automatically assign length-1 as the up state (if it is a state name obv).

Example:

``` js
    $stateProvider.state('customers', {
      url: '/customers',
      templateUrl: 'customers.htmll'
    }).state('customer', {
      url: '/customers/:id',
      templateUrl: 'customer.html'
    })
```

Rather than defining `data: { up: 'customers'}` on the customer state we can just read it from the URL.

It won't be right for all occasions, but probably for a lot. The rest can be defined just like it is now.

### CODE REVIEW

**Comment by davidpfahler** [comment]
So, the convention is that the URL must have the same first segment as the sate name? If so, I see that there is a problem with nested states. For example:

``` javascript
    $stateProvider.state('customers', {
      url: '/customers',
      templateUrl: 'customers.htmll'
    }).state('customer', {
      url: '/customers/:id',
      templateUrl: 'customer.html'
    }).state('purchases', {
        url: '/customers/:id/purchases'
        templateUrl: 'purchases.html'
    })
```

We couldn't use the segments to build the `up` state name here, because that would be `customers/:id` or `customersId` (with some magic). It's still possible to derive the state name from the Url in this case, but the developer needs to think quite alot about the conventions, so for example:

``` javascript
    $stateProvider.state('customers', {
      url: '/customers',
      templateUrl: 'customers.htmll'
    }).state('customer', {
      url: '/customers/:id',
      templateUrl: 'customer.html'
    }).state('customers/:id', {
        url: '/customers/:id/purchases'
        templateUrl: 'purchases.html'
    })
```

In this case the state name detection would work but is not intuitive to configure at all.

**Comment by boennemann** [comment]
It's about defaults, not about being right 100% of the time.
We could also just ignore cases where the upper segment starts with a colon, because then we wouldn't even default so something crazy and configuration is needed, but only in a few remaining cases.

**Comment by boennemann** [comment]
What I'm actually asking is: Do you see any downside to implement this as a default, while we clearly state that config is needed in some cases?

**Comment by davidpfahler** [comment]
Implementing a default behavior, that automates what otherwise needs configuration, is a good thing, but it needs to be consistent. I would expect automatic up state detection to work for multiple levels of navigation if it works for two levels. Here is an idea: Can we find the state not by state name but by matching the url?

If the current state's url was `/customers/:id/purchases` then the up state should have the URL `/customers/:id`. Can we detect that? I know I looked at this idea earlier and it was not trivial to get the URLs involved. But putting implementation differences aside, wouldn't that be the preferable strategy, to find the state by url and not by name?

**Comment by boennemann** [comment]
Actually there is a reason why it makes no sense at all to automatically detect up state for param urls. _Params_. Where should the id param come from for the up button? Users have to define this themselves anyways.

Having this in mind it doesn't seem reasonable to me to parse every single state for a matching url, while the url segment will be just fine for many cases.

**Comment by davidpfahler** [comment]
Yes, absolutely. I'm OK with only defaulting for the two levels then.

**Pull request merged**
