### PR TITLE
New build process

### PR DESCRIPTION
**Pull request by boennemann**
- [x] Convert old demo apps to views of the new demo app
- [x] Everything else

### CODE REVIEW

**Comment by davidpfahler** [comment]
@boennemann Let me know once this is ready for review.

**Comment by boennemann** [comment]
@davidpfahler It is, I'm finishing up the doc conversion, but you can already review this.

**Comment by davidpfahler** [comment]
@boennemann Reviewed. All good, ready for merge :+1:

**Comment by boennemann** [comment]
@davidpfahler New demo app incoming ETA T-25minutes

**Comment by boennemann** [comment]
@davidpfahler If there are no more problems, test pass etc. you should merge this.

**Pull request merged**
