### PR TITLE
Detail Disclosure Button

### PR DESCRIPTION
**Pull request by boennemann**

### CODE REVIEW

**Comment by boennemann** [comment]
@davidpfahler you might have a look already, this is still missing though:
- [x] `bp-tab` shouldn't leak active state for wrapped tap directives
- [x] detail disclosure should have default `aria-label`
- [x] find solution for android (kindof)

**Comment by boennemann** [comment]
- [x] bigger touchtarget (44px)

**Comment by boennemann** [comment]
- [ ] tests

**Comment by davidpfahler** [comment]
Reviewed, so far :+1:

**Comment by boennemann** [comment]
have you reviewed it visually/behavior, too, or just code?
—

**Comment by davidpfahler** [comment]
Reviewed both code and visuals in Chrome. Now also reviewed it on the iPhone. It's really beautiful :)

It's just a shame that transitions are still half broken on the iPhone (not related to this PR).

**Comment by boennemann** [comment]
Btw 100% test coverage (:

**Pull request merged**
